import 'dart:convert';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main()=>runApp(const KidsApp());
const burgundy=Color(0xFF6B1F2A), cream=Color(0xFFFFF8F5);

class Profile{
  String name; int stars,points; List<String> done,badges;
  Profile({required this.name,this.stars=0,this.points=0,List<String>? done,List<String>? badges}):done=done??[],badges=badges??[];
  int get level=>min(5,1+points~/100);
  String get levelName=>['المبتدئ','المتعلم','النجم الصغير','البطل','بطل المعرفة'][level-1];
  double get progress=>((points%100)/100).clamp(0.0,1.0).toDouble();
  void finish(String id){if(!done.contains(id))done.add(id);}
  void reward({int stars=0,int points=0}){this.stars+=stars;this.points+=points;if(this.points>=10&&!badges.contains('بداية جميلة'))badges.add('بداية جميلة');if(this.points>=100&&!badges.contains('نجم المعرفة'))badges.add('نجم المعرفة');if(this.stars>=10&&!badges.contains('جامع النجوم'))badges.add('جامع النجوم');}
  Map<String,dynamic> json()=>{'name':name,'stars':stars,'points':points,'done':done,'badges':badges};
  factory Profile.fromJson(Map<String,dynamic> j)=>Profile(name:j['name']??'طفلي',stars:j['stars']??0,points:j['points']??0,done:List<String>.from(j['done']??[]),badges:List<String>.from(j['badges']??[]));
}
class Store{
  static const key='profile';
  static Future<Profile?> load()async{final p=await SharedPreferences.getInstance();final s=p.getString(key);return s==null?null:Profile.fromJson(jsonDecode(s));}
  static Future<void> save(Profile p)async{final x=await SharedPreferences.getInstance();await x.setString(key,jsonEncode(p.json()));}
}
class Voice{static final t=FlutterTts();static Future<void> say(String s,{bool en=false})async{await t.setSpeechRate(.42);await t.setPitch(1.08);await t.setLanguage(en?'en-US':'ar-SA');await t.speak(s);}}

class KidsApp extends StatelessWidget{const KidsApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'تعلّم وابتسم',theme:ThemeData(useMaterial3:true,colorSchemeSeed:burgundy),builder:(c,w)=>Directionality(textDirection:TextDirection.rtl,child:w!),home:const Start());}
class Start extends StatelessWidget{const Start({super.key});@override Widget build(BuildContext c)=>FutureBuilder<Profile?>(future:Store.load(),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Scaffold(body:Center(child:CircularProgressIndicator()));return s.data==null?const Setup():Home(p:s.data!);});}

class Mascot extends StatelessWidget{final double size;const Mascot({super.key,this.size=120});@override Widget build(BuildContext c)=>SizedBox(width:size,height:size,child:CustomPaint(painter:MP()));}
class MP extends CustomPainter{@override void paint(Canvas c,Size s){final w=s.width,h=s.height;final skin=Paint()..color=const Color(0xFFFFD5B5),scarf=Paint()..color=Colors.green,dress=Paint()..color=Colors.amber,dark=Paint()..color=Colors.black87;c.drawPath(Path()..moveTo(w*.5,h*.42)..lineTo(w*.12,h)..lineTo(w*.88,h)..close(),dress);c.drawCircle(Offset(w*.5,h*.34),w*.23,skin);c.drawPath(Path()..moveTo(w*.5,h*.05)..quadraticBezierTo(w*.1,h*.12,w*.12,h*.58)..lineTo(w*.32,h*.58)..quadraticBezierTo(w*.3,h*.27,w*.5,h*.2)..quadraticBezierTo(w*.7,h*.27,w*.68,h*.58)..lineTo(w*.88,h*.58)..quadraticBezierTo(w*.9,h*.12,w*.5,h*.05)..close(),scarf);c.drawCircle(Offset(w*.42,h*.33),w*.025,dark);c.drawCircle(Offset(w*.58,h*.33),w*.025,dark);final sm=Path()..moveTo(w*.42,h*.42)..quadraticBezierTo(w*.5,h*.48,w*.58,h*.42);c.drawPath(sm,Paint()..color=dark.color..style=PaintingStyle.stroke..strokeWidth=2);}@override bool shouldRepaint(covariant CustomPainter oldDelegate)=>false;}

class Setup extends StatefulWidget{const Setup({super.key});@override State<Setup> createState()=>_SetupState();}
class _SetupState extends State<Setup>{final name=TextEditingController();@override Widget build(BuildContext c)=>Scaffold(backgroundColor:cream,body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(28),child:Column(children:[const Mascot(size:160),const Text('تعلّم وابتسم 🌙⭐',style:TextStyle(fontSize:30,fontWeight:FontWeight.bold,color:burgundy)),const SizedBox(height:10),const Text('هيا نتعلم ونلعب معاً!'),const SizedBox(height:24),TextField(controller:name,decoration:const InputDecoration(labelText:'اسم الطفل',border:OutlineInputBorder())),const SizedBox(height:18),FilledButton.icon(onPressed:()async{final p=Profile(name:name.text.trim().isEmpty?'طفلي':name.text.trim());await Store.save(p);if(c.mounted)Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>Home(p:p)));},icon:const Icon(Icons.play_arrow),label:const Text('ابدأ المغامرة',style:TextStyle(fontSize:18)))]))));}

class Home extends StatefulWidget{final Profile p;const Home({super.key,required this.p});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{Future<void> open(Widget w)async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>w));setState((){});}Widget card(String i,String t,Color col,VoidCallback f)=>InkWell(onTap:f,borderRadius:BorderRadius.circular(22),child:Container(decoration:BoxDecoration(color:col,borderRadius:BorderRadius.circular(22)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(i,style:const TextStyle(fontSize:40)),const SizedBox(height:6),Text(t,style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.bold),textAlign:TextAlign.center)])));@override Widget build(BuildContext c)=>Scaffold(backgroundColor:cream,appBar:AppBar(backgroundColor:burgundy,foregroundColor:Colors.white,title:Text('أهلاً ${widget.p.name} 🌟'),actions:[Padding(padding:const EdgeInsets.all(12),child:Text('${widget.p.stars} ⭐',style:const TextStyle(fontSize:18)))]),body:Column(children:[const Mascot(size:85),Padding(padding:const EdgeInsets.symmetric(horizontal:18),child:Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Text('${widget.p.levelName} • المستوى ${widget.p.level}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:7),LinearProgressIndicator(value:widget.p.progress,minHeight:10),Text('${widget.p.points} نقطة')])))),Expanded(child:GridView.count(padding:const EdgeInsets.all(18),crossAxisCount:2,crossAxisSpacing:14,mainAxisSpacing:14,children:[card('🔤','الحروف العربية',Colors.teal,()=>open(Learn(p:widget.p,title:'الحروف العربية',items:ar,english:false,id:'ar'))),card('🇬🇧','English Letters',Colors.blue,()=>open(Learn(p:widget.p,title:'English Letters',items:en,english:true,id:'en'))),card('🔢','الأرقام',Colors.indigo,()=>open(Learn(p:widget.p,title:'الأرقام',items:num,english:false,id:'num'))),card('🎮','ألعاب تعليمية',Colors.orange,()=>open(Game(p:widget.p))),card('🕌','تعلم إسلامي',burgundy,()=>open(Islamic(p:widget.p))),card('🎁','المكافآت',Colors.pink,()=>open(Rewards(p:widget.p))),card('🏆','تقدمي',Colors.deepPurple,()=>open(Progress(p:widget.p))) ]))]));}

const ar=['أ','ب','ت','ث','ج','ح','خ','د','ذ','ر','ز','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ك','ل','م','ن','ه','و','ي'];
const en=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'];
const num=['١','٢','٣','٤','٥','٦','٧','٨','٩','١٠'];

class Learn extends StatefulWidget{final Profile p;final String title,id;final List<String> items;final bool english;const Learn({super.key,required this.p,required this.title,required this.items,required this.english,required this.id});@override State<Learn> createState()=>_LearnState();}
class _LearnState extends State<Learn>{final seen=<int>{};bool awarded=false;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.title),backgroundColor:burgundy,foregroundColor:Colors.white),body:Column(children:[Padding(padding:const EdgeInsets.all(16),child:LinearProgressIndicator(value:seen.length/widget.items.length,minHeight:12)),Expanded(child:GridView.builder(padding:const EdgeInsets.all(16),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:4,crossAxisSpacing:12,mainAxisSpacing:12),itemCount:widget.items.length,itemBuilder:(c,i)=>InkWell(onTap:()async{await Voice.say(widget.items[i],en:widget.english);setState(()=>seen.add(i));if(seen.length==widget.items.length&&!awarded){awarded=true;widget.p.finish(widget.id);widget.p.reward(stars:1,points:10);await Store.save(widget.p);if(c.mounted)showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('ما شاء الله! 🌟'),content:const Text('أحسنت! حصلت على نجمة و10 نقاط.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('رائع!'))]));}},child:Container(decoration:BoxDecoration(color:seen.contains(i)?Colors.green.shade400:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:burgundy,width:2)),child:Center(child:Text(widget.items[i],style:TextStyle(fontSize:28,fontWeight:FontWeight.bold,color:seen.contains(i)?Colors.white:burgundy)))))))]));}

class Game extends StatefulWidget{final Profile p;const Game({super.key,required this.p});@override State<Game> createState()=>_GameState();}
class _GameState extends State<Game>{final r=Random();final pool=['أ','ب','ت','ج','د','ر','س','م','ن','و'];String target='أ';List<String> choices=[];int score=0;bool locked=false;@override void initState(){super.initState();next();}void next(){target=pool[r.nextInt(pool.length)];choices={target,...List.generate(3,(_)=>pool[r.nextInt(pool.length)])}.toList()..shuffle();locked=false;}Future<void> pick(String x)async{if(locked)return;locked=true;if(x==target){score++;widget.p.reward(stars:1,points:10);await Store.save(widget.p);await Voice.say('أحسنت ما شاء الله');}else await Voice.say('حاول مرة أخرى');setState((){});}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('صائد الحروف 🎮'),backgroundColor:burgundy,foregroundColor:Colors.white),body:Padding(padding:const EdgeInsets.all(20),child:Column(children:[Text('اختر الحرف: $target',style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:25),Wrap(spacing:12,runSpacing:12,children:choices.map((x)=>SizedBox(width:130,height:75,child:FilledButton(onPressed:()=>pick(x),child:Text(x,style:const TextStyle(fontSize:30))))).toList()),const Spacer(),Text('النتيجة: $score ⭐',style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:12),FilledButton.icon(onPressed:(){setState(next);},icon:const Icon(Icons.refresh),label:const Text('سؤال جديد'))])));}

final isl=[['بسم الله','نقول بسم الله قبل الطعام والعمل الجميل.','🤲'],['بر الوالدين','نحترم والدينا ونساعدهما ونقول كلاماً طيباً.','❤️'],['الصدق','المسلم يحب الصدق ولا يكذب.','🌟'],['آداب الطعام','نغسل أيدينا ونأكل بيميننا ونحمد الله.','🍎'],['الوضوء','نتعلم الوضوء ونحافظ على النظافة قبل الصلاة.','💧'],['الصلاة','الصلاة عبادة عظيمة ونتعلمها مع أهلنا.','🕌'],['الأخلاق الجميلة','نسلم ونساعد الآخرين ونكون لطفاء.','😊']];
class Islamic extends StatelessWidget{final Profile p;const Islamic({super.key,required this.p});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('تعلم إسلامي 🕌'),backgroundColor:burgundy,foregroundColor:Colors.white),body:ListView(padding:const EdgeInsets.all(16),children:isl.map((x)=>Card(child:ListTile(contentPadding:const EdgeInsets.all(12),leading:Text(x[2],style:const TextStyle(fontSize:35)),title:Text(x[0],style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),subtitle:Text(x[1]),trailing:IconButton(icon:const Icon(Icons.volume_up),onPressed:()=>Voice.say(x[1]))))).toList()));}

class Rewards extends StatefulWidget{final Profile p;const Rewards({super.key,required this.p});@override State<Rewards> createState()=>_RewardsState();}
class _RewardsState extends State<Rewards>{final items=[['🎨','لون جميل',3],['⭐','ملصق نجمة',5],['🏅','وسام البطل',10],['👑','تاج المعرفة',15]];@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('المكافآت 🎁'),backgroundColor:burgundy,foregroundColor:Colors.white),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Text('نجومك: ${widget.p.stars} ⭐',style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold)))),...items.map((x)=>Card(child:ListTile(leading:Text(x[0] as String,style:const TextStyle(fontSize:35)),title:Text(x[1] as String),subtitle:Text('${x[2]} نجوم'),trailing:FilledButton(onPressed:widget.p.stars>=x[2] as int?()async{widget.p.stars-=x[2] as int;await Store.save(widget.p);setState((){});}:null,child:const Text('افتح'))))]));}
class Progress extends StatelessWidget{final Profile p;const Progress({super.key,required this.p});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('تقدمي 🏆'),backgroundColor:burgundy,foregroundColor:Colors.white),body:ListView(padding:const EdgeInsets.all(18),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[Text('${p.levelName} • المستوى ${p.level}',style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold)),const SizedBox(height:12),LinearProgressIndicator(value:p.progress,minHeight:12),const SizedBox(height:8),Text('${p.points} نقطة • ${p.stars} نجمة')] ))),const SizedBox(height:14),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('الشارات 🎖️',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),if(p.badges.isEmpty)const Padding(padding:EdgeInsets.only(top:10),child:Text('أكمل الأنشطة لتحصل على شارات!')) else ...p.badges.map((b)=>ListTile(leading:const Icon(Icons.workspace_premium,color:Colors.amber),title:Text(b)))]))),const SizedBox(height:14),Card(child:ListTile(title:const Text('الأنشطة المكتملة'),trailing:Text('${p.done.length}')))]));}
